

from django.core.exceptions import ValidationError
from rest_framework.validators import ValidationError as ApiError


def limit_question_tags(tag):
    pass
